// <auto-generated />
using System;
using Clinic_CRM.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic_CRM.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251223135401_notifyRole")]
    partial class notifyRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BranchSettingMedicalProfessional", b =>
                {
                    b.Property<int>("BranchesId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalProfessionalsId")
                        .HasColumnType("int");

                    b.HasKey("BranchesId", "MedicalProfessionalsId");

                    b.HasIndex("MedicalProfessionalsId");

                    b.ToTable("BranchSettingMedicalProfessional");
                });

            modelBuilder.Entity("BranchSettingMedicalService", b =>
                {
                    b.Property<int>("BranchesId")
                        .HasColumnType("int");

                    b.Property<int>("DentistryServicesId")
                        .HasColumnType("int");

                    b.HasKey("BranchesId", "DentistryServicesId");

                    b.HasIndex("DentistryServicesId");

                    b.ToTable("BranchSettingMedicalService");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchSettingId")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CanceledById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompletedById")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("DentistryId")
                        .HasColumnType("int");

                    b.Property<int>("DentistryServiceId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalProfessionalId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ReservationTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchSettingId");

                    b.HasIndex("CanceledById");

                    b.HasIndex("CompletedById");

                    b.HasIndex("DentistryServiceId");

                    b.HasIndex("MedicalProfessionalId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActivatedById")
                        .HasColumnType("int");

                    b.Property<string>("ActivationRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RequestRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestedById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RequestedById");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Clinic_CRM.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchSettingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MedicalProfessionalId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WeekDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchSettingId");

                    b.HasIndex("MedicalProfessionalId");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("Clinic_CRM.Models.MedicalProfessional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationalBackground")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresUserAccount")
                        .HasColumnType("bit");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MedicalProfessionals");
                });

            modelBuilder.Entity("Clinic_CRM.Models.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MedicalServices");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Clinic_CRM.Models.OTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("OtpHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId1")
                        .HasColumnType("int");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresUserAccount")
                        .HasColumnType("bit");

                    b.Property<string>("SubCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId1");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CanceledById")
                        .HasColumnType("int");

                    b.Property<string>("CanceledRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CheckRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentProof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectedById")
                        .HasColumnType("int");

                    b.Property<string>("RejectionRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestedById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnPaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CanceledById");

                    b.HasIndex("CardId");

                    b.HasIndex("CheckedById");

                    b.HasIndex("RejectedById");

                    b.HasIndex("RequestedById");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.BranchSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanySettingId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanySettingId");

                    b.ToTable("BranchSettings");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.CardSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpirationDuration")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardTypeId");

                    b.ToTable("CardSettings");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.CompanySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CompanySetting");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.UserOnBoardingSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUploaded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserOnBoardingSettings");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.WorkingDaySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<int>("CompanySettingId")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CompanySettingId");

                    b.ToTable("Workdays");
                });

            modelBuilder.Entity("Clinic_CRM.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Clinic_CRM.Models.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Clinic_CRM.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAddBank")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddBankAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddBranchSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddCardSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddCardType")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddDoctorSchedule")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddMedicalProfessional")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddMedicalService")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddPatient")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddRole")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddUserOnBoarding")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddWorkingSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanApproveCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCancelAppointment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCancelCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCheckCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCompleteAppointment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditAppointment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditBank")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditBankAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditBranchSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditCard")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditCardSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditCardType")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditCompanySettings")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditDoctorSchedule")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditMedicalProfessional")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditPatient")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditRole")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditUserOnBoarding")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditWorkingSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanMakeAppointment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRejectCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRequestCard")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRequestCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateMedicalService")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewAppointment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewBank")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewBankAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewBranchSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewCard")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewCardPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewCardSetting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewCardType")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewCompanySettings")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewDoctorSchedule")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewMedicalProfessional")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewMedicalService")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewPatient")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewRole")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewUserOnBoardingSetting")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MedicalProfessionalMedicalService", b =>
                {
                    b.Property<int>("MedicalProfessionalsId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalServicesId")
                        .HasColumnType("int");

                    b.HasKey("MedicalProfessionalsId", "MedicalServicesId");

                    b.HasIndex("MedicalServicesId");

                    b.ToTable("MedicalProfessionalMedicalService");
                });

            modelBuilder.Entity("BranchSettingMedicalProfessional", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.BranchSetting", null)
                        .WithMany()
                        .HasForeignKey("BranchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.MedicalProfessional", null)
                        .WithMany()
                        .HasForeignKey("MedicalProfessionalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchSettingMedicalService", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.BranchSetting", null)
                        .WithMany()
                        .HasForeignKey("BranchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.MedicalService", null)
                        .WithMany()
                        .HasForeignKey("DentistryServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_CRM.Models.Appointment", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.BranchSetting", "BranchSetting")
                        .WithMany("Appointments")
                        .HasForeignKey("BranchSettingId");

                    b.HasOne("Clinic_CRM.Models.User", "CanceledBy")
                        .WithMany()
                        .HasForeignKey("CanceledById");

                    b.HasOne("Clinic_CRM.Models.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById");

                    b.HasOne("Clinic_CRM.Models.MedicalService", "DentistryService")
                        .WithMany()
                        .HasForeignKey("DentistryServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.MedicalProfessional", "MedicalProfessionals")
                        .WithMany()
                        .HasForeignKey("MedicalProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("BranchSetting");

                    b.Navigation("CanceledBy");

                    b.Navigation("CompletedBy");

                    b.Navigation("DentistryService");

                    b.Navigation("MedicalProfessionals");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Card", b =>
                {
                    b.HasOne("Clinic_CRM.Models.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");

                    b.HasOne("Clinic_CRM.Models.Settings.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById");

                    b.Navigation("ActivatedBy");

                    b.Navigation("CardType");

                    b.Navigation("Patient");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Clinic_CRM.Models.DoctorSchedule", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.BranchSetting", "BranchSetting")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("BranchSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.MedicalProfessional", "MedicalProfessionals")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("MedicalProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchSetting");

                    b.Navigation("MedicalProfessionals");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Patient", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId1");

                    b.HasOne("Clinic_CRM.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Payment", b =>
                {
                    b.HasOne("Clinic_CRM.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinic_CRM.Models.User", "CanceledBy")
                        .WithMany()
                        .HasForeignKey("CanceledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinic_CRM.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.User", "CheckedBy")
                        .WithMany()
                        .HasForeignKey("CheckedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinic_CRM.Models.User", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById");

                    b.HasOne("Clinic_CRM.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedBy");

                    b.Navigation("CanceledBy");

                    b.Navigation("Card");

                    b.Navigation("CheckedBy");

                    b.Navigation("RejectedBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.BankAccount", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.BranchSetting", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.CompanySetting", null)
                        .WithMany("Branches")
                        .HasForeignKey("CompanySettingId");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.CardSetting", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId");

                    b.Navigation("CardType");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.WorkingDaySetting", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Settings.CompanySetting", "CompanySetting")
                        .WithMany("Workdays")
                        .HasForeignKey("CompanySettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySetting");
                });

            modelBuilder.Entity("Clinic_CRM.Models.User", b =>
                {
                    b.HasOne("Clinic_CRM.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Clinic_CRM.Models.UserNotification", b =>
                {
                    b.HasOne("Clinic_CRM.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalProfessionalMedicalService", b =>
                {
                    b.HasOne("Clinic_CRM.Models.MedicalProfessional", null)
                        .WithMany()
                        .HasForeignKey("MedicalProfessionalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_CRM.Models.MedicalService", null)
                        .WithMany()
                        .HasForeignKey("MedicalServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_CRM.Models.MedicalProfessional", b =>
                {
                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.Bank", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.BranchSetting", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("Clinic_CRM.Models.Settings.CompanySetting", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Workdays");
                });

            modelBuilder.Entity("Clinic_CRM.Models.User", b =>
                {
                    b.Navigation("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
